# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/rp_690t.xci
# IP: The module: 'rp_690t' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/source/rp_690t-PCIE_X0Y2.xdc
# XDC: The top module name and the constraint reference have the same name: 'rp_690t'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/synth/rp_690t_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rp_690t'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/rp_690t.xci
# IP: The module: 'rp_690t' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/source/rp_690t-PCIE_X0Y2.xdc
# XDC: The top module name and the constraint reference have the same name: 'rp_690t'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/synth/rp_690t_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rp_690t'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
