# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo.xci
# IP: The module: 'ep_cq_to_rp_rq_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_cq_to_rp_rq_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_cq_to_rp_rq_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_cq_to_rp_rq_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo.xci
# IP: The module: 'ep_cq_to_rp_rq_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_cq_to_rp_rq_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_cq_to_rp_rq_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_cq_to_rp_rq_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
