# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx690tffg1157-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/zhoulian/work/hxzy/cy/gen2/bypass/boards/690t/bypass_690t/bypass_690t.cache/wt [current_project]
set_property parent.project_path /home/zhoulian/work/hxzy/cy/gen2/bypass/boards/690t/bypass_690t/bypass_690t.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/zhoulian/work/hxzy/cy/gen2/bypass/boards/690t/bypass_690t/bypass_690t.cache/ip [current_project]
set_property ip_cache_permissions disable [current_project]
set src_rc [catch { 
  puts "source /home/zhoulian/work/hxzy/cy/gen2/bypass/boards/690t/bypass_690t/ip_patch/process_control/synthesis_pre.tcl"
  source /home/zhoulian/work/hxzy/cy/gen2/bypass/boards/690t/bypass_690t/ip_patch/process_control/synthesis_pre.tcl
} _RESULT] 
if {$src_rc} { 
  send_msg_id runtcl-1 error "$_RESULT"
  send_msg_id runtcl-2 error "sourcing script /home/zhoulian/work/hxzy/cy/gen2/bypass/boards/690t/bypass_690t/ip_patch/process_control/synthesis_pre.tcl failed"
  return -code error
}
read_mem /home/zhoulian/work/hxzy/cy/gen2/bypass/rom/cgator_cfg_rom_yh_server_veiglo_xmc.data
read_verilog -library xil_defaultlib {
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/cgator.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/cgator_controller.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/cgator_cpl_decoder.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/cgator_pkt_generator.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/cgator_tx_mux.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/cgator_wrapper.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/ep.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/rp.v
  /home/zhoulian/work/hxzy/cy/gen2/bypass/src_690t/bypass_690t.v
}
read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/ep_690t_veiglo_xmc.xci
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/source/ep_690t_veiglo_xmc-PCIE_X0Y1.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/synth/ep_690t_veiglo_xmc_ooc.xdc]

read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo.xci
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_cq_to_rp_rq_fifo_1/ep_cq_to_rp_rq_fifo_ooc.xdc]

read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_ila_1/ep_ila.xci
set_property used_in_synthesis false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_ila_1/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_ila_1/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_ila_1/ep_ila_ooc.xdc]

read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_rc_to_rp_cc_fifo_1/ep_rc_to_rp_cc_fifo.xci
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_rc_to_rp_cc_fifo_1/ep_rc_to_rp_cc_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_rc_to_rp_cc_fifo_1/ep_rc_to_rp_cc_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_rc_to_rp_cc_fifo_1/ep_rc_to_rp_cc_fifo_ooc.xdc]

read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/rp_690t.xci
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/source/rp_690t-PCIE_X0Y2.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_690t_1/synth/rp_690t_ooc.xdc]

read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_cq_to_ep_rq_fifo_1/rp_cq_to_ep_rq_fifo.xci
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_cq_to_ep_rq_fifo_1/rp_cq_to_ep_rq_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_cq_to_ep_rq_fifo_1/rp_cq_to_ep_rq_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_cq_to_ep_rq_fifo_1/rp_cq_to_ep_rq_fifo_ooc.xdc]

read_ip -quiet /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_rc_to_ep_cc_fifo_1/rp_rc_to_ep_cc_fifo.xci
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_rc_to_ep_cc_fifo_1/rp_rc_to_ep_cc_fifo.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_rc_to_ep_cc_fifo_1/rp_rc_to_ep_cc_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/rp_rc_to_ep_cc_fifo_1/rp_rc_to_ep_cc_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/zhoulian/work/hxzy/cy/gen2/bypass/xdc_690t/bypass.xdc
set_property used_in_implementation false [get_files /home/zhoulian/work/hxzy/cy/gen2/bypass/xdc_690t/bypass.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top bypass_690t -part xc7vx690tffg1157-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bypass_690t.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bypass_690t_utilization_synth.rpt -pb bypass_690t_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
