# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/top_ep_ila.xci
# IP: The module: 'top_ep_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ep_ila'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ep_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/top_ep_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ep_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/top_ep_ila.xci
# IP: The module: 'top_ep_ila' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ep_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ep_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/top_ep_ila_2/top_ep_ila_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_ep_ila'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
