# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/ep_690t_veiglo_xmc.xci
# IP: The module: 'ep_690t_veiglo_xmc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/source/ep_690t_veiglo_xmc-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_690t_veiglo_xmc'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/synth/ep_690t_veiglo_xmc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_690t_veiglo_xmc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/ep_690t_veiglo_xmc.xci
# IP: The module: 'ep_690t_veiglo_xmc' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/source/ep_690t_veiglo_xmc-PCIE_X0Y1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_690t_veiglo_xmc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/zhoulian/work/hxzy/cy/gen2/bypass/ips_690t/ep_690t_veiglo_xmc_1/synth/ep_690t_veiglo_xmc_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ep_690t_veiglo_xmc'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
